Repository harseille/WhatSsub, pull requests merged in 2022-11, with the labels that each got.

#8 :wrench: init husky
  .eslintrc.json
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc.json
  babel.config.json
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: 설계

#34 :lipstick: add IngredientCard, add mixin
  src/assets/images/ingredients/sauce_hot_chilli.png
  src/components/IngredientCard.tsx
  src/pages/Home.tsx
  src/styles/global.ts
  src/styles/mixin.ts
  src/styles/theme.ts
  src/types/styled.d.ts
Labels: 개발

#36 Feature/component combination ingredient list
  src/assets/images/ingredients/sauce_hot_chilli.png
  src/components/CombinationIngredientList.tsx
  src/components/IngredientCard.tsx
  src/pages/Home.tsx
  src/styles/global.ts
  src/styles/mixin.ts
  src/styles/theme.ts
  src/types/styled.d.ts
Labels: 개발

#43 Feature/component combination ranking card
  src/components/CombinationIngredientList.tsx
  src/components/CombinationRankingCard.tsx
  src/components/IngredientCard.tsx
  src/components/Like.tsx
  src/pages/Home.tsx
  src/styles/mixin.ts
Labels: 개발

#50 Feature/component header nav
  src/assets/images/custom.svg
  src/assets/images/home.svg
  src/assets/images/logo.svg
  src/assets/images/myPage.svg
  src/assets/images/ranking.svg
  src/components/Header.tsx
  src/components/HeaderItemsWrap.tsx
  src/index.tsx
  src/layouts/RootLayout.tsx
  src/pages/Home.tsx
  src/pages/Ranking.tsx
  src/styles/global.ts
  src/types/asset.d.ts
Labels: 개발

#51 :lipstick: add Button
  src/components/IngredientCard.tsx
  src/components/UI/Button.tsx
  src/pages/Home.tsx
Labels: 개발

#55 :lipstick: add IngredientCardList
  src/components/CombinationIngredientList.tsx
  src/components/IngredientCard.tsx
  src/components/IngredientCardList.tsx
  src/pages/Home.tsx
Labels: 개발

#71 :lipstick: add BestCombinationDetailPage
  src/components/CombinationRankingCard.tsx
  src/components/CommentItem.tsx
  src/components/CommentList.tsx
  src/components/Like.tsx
  src/pages/BestCombinationDetail.tsx
  src/router.tsx
  src/types/ISandwitch.ts
Labels: 개발

#73 :lipstick: update CombinationIngredientList
  src/components/CombinationIngredientList.tsx
  src/pages/BestCombinationDetail.tsx
  tsconfig.json
Labels: 개발

#76 :bug: solve nested routes path problem
  src/App.tsx
  src/components/CombinationRankingCard.tsx
  src/components/HeaderItemsWrap.tsx
  src/components/Like.tsx
  src/router.tsx
  webpack.config.js
Labels: 개발

#88 :sparkles: add firebase OAuth
  .env.dev
  .gitignore
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/firebase.config.ts
  src/pages/BestCombinationDetailPage.tsx
  src/pages/LoginPage.tsx
  webpack.config.js
Labels: 개발

#89 ✨ add Firebase
  .env.dev
  .gitignore
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/firebase.config.ts
  src/pages/BestCombinationDetailPage.tsx
  src/pages/LoginPage.tsx
  webpack.config.js
Labels: 개발

#92 Feature/add ingredients data
  .env.dev
  src/assets/images/ingredients/additional/Omelet.png
  src/assets/images/ingredients/additional/avocado.png
  src/assets/images/ingredients/additional/double.png
  src/assets/images/ingredients/bread/Flat_Bread.png
  src/assets/images/ingredients/bread/Hearty_Italian.png
  src/assets/images/ingredients/bread/Honey_Oat.png
  src/assets/images/ingredients/bread/Parmesan_Oregano.png
  src/assets/images/ingredients/bread/Wheat.png
  src/assets/images/ingredients/bread/White.png
  src/assets/images/ingredients/cheese/American_Cheese.png
  src/assets/images/ingredients/cheese/Mozzarella_Cheese.png
  src/assets/images/ingredients/cheese/Shredded_Cheese.png
  src/assets/images/ingredients/main/bacon.png
  src/assets/images/ingredients/main/chicken_breast.png
  src/assets/images/ingredients/main/chicken_teriyaki.png
  src/assets/images/ingredients/main/egg_mayo.png
  src/assets/images/ingredients/main/ham.png
  src/assets/images/ingredients/main/mushroom.png
  src/assets/images/ingredients/main/pepperoni.png
  src/assets/images/ingredients/main/pulled_pork.png
  src/assets/images/ingredients/main/rotisserie.png
  src/assets/images/ingredients/main/salami.png
  src/assets/images/ingredients/main/shrimp.png
  src/assets/images/ingredients/main/spicy_bbq.png
  src/assets/images/ingredients/main/steak.png
  src/assets/images/ingredients/main/tuna.png
  src/assets/images/ingredients/main/turkey.png
  src/assets/images/ingredients/main/veggie.png
  src/assets/images/ingredients/sauce/Honey_Mustard.png
  src/assets/images/ingredients/sauce/Italian_Dressing.png
  src/assets/images/ingredients/sauce/Red_Wine.png
  src/assets/images/ingredients/sauce/Salt.png
  src/assets/images/ingredients/sauce/Yellow_Mustard.png
  src/assets/images/ingredients/sauce/black_pepper.png
  src/assets/images/ingredients/sauce/horseradish.png
  src/assets/images/ingredients/sauce/hot_chilli.png
  src/assets/images/ingredients/sauce/mayonnaise.png
  src/assets/images/ingredients/sauce/olive_oil.png
  src/assets/images/ingredients/sauce/ranch.png
  src/assets/images/ingredients/sauce/smoke_bbq.png
  src/assets/images/ingredients/sauce/southwest_chipotle.png
  src/assets/images/ingredients/sauce/sweet_chilli.png
  src/assets/images/ingredients/sauce/sweet_onion.png
  src/assets/images/ingredients/sauce_hot_chilli.png
  src/assets/images/ingredients/vegetable/Avocado.png
  src/assets/images/ingredients/vegetable/Cucumbers.png
  src/assets/images/ingredients/vegetable/Jalapenos.png
  src/assets/images/ingredients/vegetable/Lettuce.png
  src/assets/images/ingredients/vegetable/Olives.png
  src/assets/images/ingredients/vegetable/Peppers.png
  src/assets/images/ingredients/vegetable/Pickles.png
  src/assets/images/ingredients/vegetable/Red_Onions.png
  src/assets/images/ingredients/vegetable/Tomatoes.png
  src/data/ingredients.json
Labels: 문서

#101 :pencil2: 진행도 수정 시 임시로 textContent 사용하던 참조 값 수정
  src/components/CustomCombination/MyCombinationStep.tsx
  src/pages/CustomCombinationPage.tsx
Labels: 수정

#106 Feature/o auth login
  src/App.tsx
  src/pages/LoginPage.tsx
  src/state/index.ts
  src/state/isLoggedIn.ts
  src/state/user.ts
  src/utils/getOAuthProvider.ts
  src/utils/index.ts
  tsconfig.json
  webpack.config.js
Labels: 개발

#108 :bug: solve type error caused by 매인재료
  src/components/UI/Cards/SandwitchInfoCard.tsx
  src/pages/BestCombinationDetailPage.tsx
Labels: 버그

#112 Feature/login redirect
  src/App.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/pages/LoginPage.tsx
  src/utils/getOAuthProvider.ts
  src/utils/getSessionUserInfo.ts
  src/utils/index.ts
Labels: 개발

#118 Feature/page best combination detail
  public/data/bestCombination.json
  src/components/IngredientCardList.tsx
  src/components/UI/Cards/IngredientCard.tsx
  src/constants/constants.ts
  src/pages/BestCombinationDetailPage.tsx
  src/pages/index.tsx
  src/router.tsx
  src/types/ISandwich.ts
Labels: 개발

#121 Fix/path error
  src/components/UI/Cards/SandwichInfoCard.tsx
  src/pages/BestCombinationDetailPage.tsx
Labels: 버그

#127 :sparkles: comment리스트 view 완료
  public/data/꿀조합/bestCombination.json
  src/App.tsx
  src/components/CommentItem.tsx
  src/components/Comments/CommentList.tsx
  src/firebase.config.ts
  src/pages/BestCombinationDetailPage.tsx
Labels: 개발

#128 ✨ click "꿀조합"card liked_button to chagne icon
  src/assets/icons/heart-fill.svg
  src/assets/icons/heart.svg
  src/assets/images/heart.png
  src/components/UI/Cards/SandwichInfoCard.tsx
  src/pages/BestCombinationListPage.tsx
  src/state/user.ts
Labels: 개발

#133 :sparkles: 새 댓글 추가 기능
  src/api/addNewComment.ts
  src/api/getCommentList.ts
  src/api/index.ts
  src/components/CommentItem.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentList.tsx
  src/firebase.config.ts
  src/pages/BestCombinationDetailPage.tsx
  src/types/IComment.ts
  tsconfig.json
  webpack.config.js
Labels: 개발

#134 :sparkles: 로그인 redirect 처리 : 헤더, 로그인, 마이페이지, 로그아웃 기능 추가
  node_modules/.bin/ansi-html
  src/App.tsx
  src/layouts/HeaderItemsWrap.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPagePage.tsx
  src/utils/getOAuthProvider.ts
Labels: 개발

#139 :truck: 전체 types, pages 한글화 통일, Components 구조 변경, import 순서 통일
  src/App.tsx
  src/api/addNewComment.ts
  src/api/index.ts
  src/components/Attribute/AttributeBadge.tsx
  src/components/Attribute/AttributeBadgeList.tsx
  src/components/Attribute/AttributeButton.tsx
  src/components/Attribute/AttributeButtonList.tsx
  src/components/CommentInputWrap.tsx
  src/components/CommentItem.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentList.tsx
  src/components/Common/Button/Like.tsx
  src/components/Common/Cards/MyCombinationCard.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/CustomCombination/CustomStep.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/CustomCombination/MyCombinationStep.tsx
  src/components/CustomCombination/NextStepButton.tsx
  src/components/CustomCombination/SelectComponent.tsx
  src/components/Ingredient/CombinationIngredientList.tsx
  src/components/Ingredient/IngredientCard.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Roulette/RandomModalResult.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/components/SandwichBadgeList.tsx
  src/components/Sandwichs/SandwichInfo.tsx
  src/components/UI/Button.tsx
  src/components/UI/RandomModalResult.tsx
  src/data/PickPageDummy.ts
  src/layouts/Header.tsx
  src/layouts/HeaderItemsWrap.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/pages/BestCombinationListPage.tsx
  src/pages/BestCombinationPickPage.tsx
  src/pages/CustomCombinationPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPagePage.tsx
  src/pages/RandomPickPage.tsx
  src/pages/RankingPage.tsx
  src/pages/index.tsx
  src/types/ISandwich.ts
  src/utils/filterBestCombinationList.ts
  tsconfig.json
Labels: 리팩토링

#141 ♻️ firebase 공통부 로직 처리
  src/api/dbGet.ts
  src/api/dbPush.ts
  src/components/Roulette/RandomRoulette.tsx
  src/components/SandwichBadgeList.tsx
  src/components/Sandwichs/SandwichInfo.tsx
  tsconfig.json
Labels: 리팩토링

#143 :sparkles: add custom_hook for Infinite_Scroll
  src/hooks/useInfiniteScroll.ts
  src/pages/BestCombinationListPage.tsx
Labels: 개발

#145 ✨ add custom_hook for Scroll_Top
  src/components/Common/Button/Top.tsx
  src/hooks/useScrollTop.ts
  src/layouts/RootLayout.tsx
  src/pages/BestCombinationListPage.tsx
  tsconfig.json
  webpack.config.js
Labels: 개발

#147 :sparkles: move to top of scroll when routing
  src/layouts/RootLayout.tsx
Labels: 개발

#148 :sparkles: 댓글리스트 불러오기
  src/App.tsx
  src/api/addNewComment.ts
Labels: 개발

#150 :memo: README.md 수정
  README.md
Labels: 문서

#151 :memo: README.md 수정
  README.md
Labels: 문서

#152 :memo: README.md 수정
  README.md
Labels: 문서

#155 ♻️ add useToggleFilter & separate filter_state_Management from BestCombinationPickPage
  README.md
  src/hooks/useToggleFilter.ts
  src/pages/BestCombinationPickPage.tsx
Labels: 리팩토링

#162 ♻️ to separate components of BestCombinationPickPage
  .husky/pre-commit
  src/assets/images/pick_page_desktop_sandwich.png
  src/components/BestCombinationPick/DeskTopImage.tsx
  src/components/BestCombinationPick/IngredientButtonListContainer.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/UI/Button.tsx
  src/hooks/useToggleFilter.ts
  src/pages/BestCombinationPickPage.tsx
Labels: 개발

#164 Feature/get comment list
  src/api/addNewComment.ts
  src/api/dbPush.ts
  src/api/getCommentList.ts
  src/api/index.ts
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/firebase.config.ts
  src/hooks/useGetComments.ts
  src/pages/BestCombinationDetailPage.tsx
  src/state/BestCombinationId.ts
  src/state/IsAddComment.ts
  src/state/UpdateComments.ts
  src/state/index.ts
Labels: 개발, 리팩토링

#168 ✨ Feature add comment, read comments / edit Comment Input Desktop UI
  src/api/addNewComment.ts
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentList.tsx
  src/hooks/useGetComments.ts
  src/state/BestCombinationId.ts
  src/state/IsAddComment.ts
  src/state/UpdateComments.ts
  src/state/index.ts
  src/state/user.ts
  src/types/IComment.ts
Labels: 개발

#170 ✨ Feature/best_combination_page get Firebase Data
  public/data/ingredients.json
  src/firebase.config.ts
  src/hooks/useGetComments.ts
  src/pages/BestCombinationDetailPage.tsx
  src/utils/getFirebaseImgaURL.ts
Labels: 개발

#171 ✨ Feature/get comment time by create time
  src/components/Comments/CommentItem.tsx
  src/hooks/useGetComments.ts
  src/types/IComment.ts
  src/utils/getTimePassedBy.ts
  src/utils/index.ts
  src/utils/setFirebaseImgaURL.ts
Labels: 개발

#172 Feature/page home page
  src/pages/HomePage.tsx
Labels: 개발

#173 :sparkles: Firebase dbPush
  src/api/dbPush.ts
  src/hooks/useGetComments.ts
Labels: 개발

#176 ♻️ refactor Comment input Wrap UI , add feature initialize Comment input when it done
  src/api/dbGet.ts
  src/api/dbPush.ts
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/layouts/RootLayout.tsx
  src/pages/LoginPage.tsx
  src/state/index.ts
Labels: 리팩토링

#181 :sparkles: Comments ordering
  src/api/addNewComment.ts
  src/components/Comments/CommentItem.tsx
  src/components/Comments/CommentList.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Ingredient/IngredientCard.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/hooks/useGetComments.ts
  src/pages/BestCombinationDetailPage.tsx
  src/typings/IComment.ts
Labels: 개발

#184 ♻️ modify type & merge_error
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/CustomCombination/CombinationRegistration.tsx
  src/components/CustomCombination/CustomPageWrap.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/CustomCombination/SelectCombination.tsx
  src/components/CustomCombination/SelectComponent.tsx
  src/components/Ranking/RankingList.tsx
  src/pages/MyPagePage.tsx
  src/pages/RankingPage.tsx
  src/typings/ISandwich.ts
  src/utils/customCombination/combinationVerification.ts
  src/utils/customCombination/postCustom.ts
  src/utils/customCombination/selectIngredients.ts
Labels: 수정, 리팩토링

#189 Feature/refactoring type conneting firebase
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/RankingPage.tsx
Labels: 개발, 수정

#193 :lipstick: 단찌 배치
  src/components/Roulette/RandomRoulette.tsx
  src/pages/RandomPickPage.tsx
Labels: 개발

#197 :recycle: modify Top-Button Position
  src/components/Common/Button/Top.tsx
Labels: 리팩토링

#200 :sparkles: add feature comment_inifinity_scroll
  src/api/index.ts
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentList.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useComments.ts
  src/hooks/useGetComments.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/BestCombinationDetailPage.tsx
  src/pages/RankingPage.tsx
  src/utils/addNewComment.ts
  src/utils/index.ts
Labels: 개발

#207 Feature/component modal
  .eslintrc.json
  public/index.html
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/UI/Button.tsx
  src/components/UI/Modal.tsx
  src/hooks/useCheckLogin.ts
  src/hooks/useToggleFilter.ts
  src/pages/BestCombinationPickPage.tsx
Labels: 개발

#208 :lipstick: add Modal_Component styling for mobile
  src/components/UI/Modal.tsx
Labels: 수정

#211 :lipstick: add styling when hover button on Pick&List_Page
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/BestCombinationList/NotFoundBestCombinationList.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/UI/Modal.tsx
Labels: 리팩토링

#212 :lipstick: add styling when hover button on Pick&List_Page_#2
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/BestCombinationPick/IngredientButtonListContainer.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/pages/BestCombinationPickPage.tsx
Labels: 리팩토링

#214 ♻️ abstractive login page and best combiantion detail page
  src/api/dbDelete.ts
  src/api/index.ts
  src/components/BestCombinationDetail/Contents.tsx
  src/components/BestCombinationDetail/Header.tsx
  src/components/BestCombinationDetail/index.tsx
  src/components/Login/Banner.tsx
  src/components/Login/ButtonList.tsx
  src/components/Login/index.tsx
  src/components/Ranking/RankingList.tsx
  src/components/UI/Button.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/pages/LoginPage.tsx
Labels: 리팩토링

#217 :sparkles: 삭제버튼 기능 구현 및 상태 리팩토링
  src/pages/MyPagePage.tsx
Labels: 개발, 리팩토링

#219 :sparkles: delete bestCombination transaction control
  src/hooks/useDeleteBestCombination.tsx
Labels: 개발

#221 Feature/combination
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/CustomCombination/CombinationRegistration.tsx
  src/components/CustomCombination/CustomPageModal.tsx
  src/components/CustomCombination/CustomPageWrap.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/CustomCombination/MyCombinationCard.tsx
  src/components/CustomCombination/SelectCombination.tsx
  src/components/CustomCombination/SelectComponent.tsx
  src/utils/customCombination/postCustom.ts
  src/utils/customCombination/selectIngredients.ts
Labels: 리팩토링

#222 :sparkles: 404 page
  src/assets/images/danzzi/danzzi_QM.png
  src/assets/images/danzzi/danzzi_speechless.png
  src/pages/BestCombinationDetailPage.tsx
  src/pages/NotFound.tsx
  src/pages/index.tsx
  src/router.tsx
Labels: 개발

#224 Feature/sort ingredient card list
  src/components/BestCombinationDetail/Contents.tsx
  src/components/Ingredient/IngredientCard.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/components/UI/Button.tsx
  src/components/UI/Span.tsx
  src/constants/constants.ts
  src/pages/BestCombinationDetailPage.tsx
  src/pages/NotFound.tsx
  src/typings/ISandwich.ts
Labels: 개발

#225 ♻️ add Attribute as QueryString
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/BestCombinationPick/IngredientButtonListContainer.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/pages/BestCombinationPickPage.tsx
  src/utils/changeAttrToQueryString.ts
Labels: 리팩토링

#230 :recycle: refacoring remove type any
  src/api/dbUpdate.ts
  src/components/BestCombinationDetail/Header.tsx
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Comments/CommentItem.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/constants/constants.ts
  src/hooks/useComments.ts
  src/pages/BestCombinationDetailPage.tsx
  src/typings/ISandwich.ts
Labels: 개발

#237 :recycle: modify from modal to text_color_red when maxSelectedAttr_Error
  src/components/BestCombinationAttribute/AttributeButtonList.tsx
  src/components/BestCombinationPick/IngredientButtonListContainer.tsx
  src/hooks/useToggleFilter.ts
  src/pages/BestCombinationPickPage.tsx
Labels: 리팩토링

#239 ♻️ Refactoring for PickPage rendering optimization
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/BestCombinationAttribute/AttributeButtonList.tsx
  src/components/BestCombinationAttribute/AttributeListTitle.tsx
  src/components/BestCombinationPick/AttributeButtonListContainer.tsx
  src/components/BestCombinationPick/DeskTopImage.tsx
  src/components/BestCombinationPick/IngredientButtonListContainer.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/BestCombinationPick/RefreshButton.tsx
  src/hooks/useToggleFilter.ts
  src/pages/BestCombinationPickPage.tsx
Labels: 리팩토링

#242 Feature/page ranking page
  src/api/getRankingList.ts
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/components/Ranking/RankingTab.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/RankingPage.tsx
  src/styles/theme.ts
  src/typings/styled.d.ts
Labels: 버그, 리팩토링

#243 :sparkles: ingredientCard scroll
  src/components/Ingredient/IngredientCardList.tsx
Labels: 개발

#244 :recycle: Refactoring for ListPage rendering optimization
  src/App.tsx
  src/api/getFilteredBestCombination.ts
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Common/Button/LikeRed.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/Common/SandwichInfo.tsx
  src/hooks/useCheckLogin.ts
  src/pages/BestCombinationListPage.tsx
Labels: 리팩토링

#245 :memo: delete hook 리팩토링
  src/components/BestCombinationDetail/Contents.tsx
  src/components/Common/UI/Modal.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/hooks/useDeleteBestCombination.ts
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#246 ♻️ Refactoring for ListPage rendering optimization #2
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/hooks/useLikedBestCombination.ts
Labels: 리팩토링

#248 :ambulance: initialize like when user login
  src/services/Firebase/Auth/getOAuthProvider.ts
Labels: 핫픽스

#250 🚑 Sync LikeList When Clicked like_button
  src/hooks/useLikedBestCombination.ts
Labels: 핫픽스

#251 :bug: solve comment count update not active
  src/api/getCommentListCount.ts
  src/api/pushNewComment.ts
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentsContainer.tsx
  src/hooks/useComments.ts
  src/hooks/useInfiniteScroll.ts
Labels: 개발

#255 :recycle: MyPage refactoring
  src/api/getBestCombination.ts
  src/components/MyPage/LikeCombinationList.tsx
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/UserCombinatonList.tsx
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#256 Feature/page ranking
  src/assets/icons/loading_sandwich.svg
  src/components/Common/Button/Like.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useInfiniteScroll.ts
  src/utils/getYearMonthDate.ts
Labels: 개발

#260 :pencil2: delete comments and useless codes
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/pages/MyPagePage.tsx
Labels: 수정

#261 :bug: solve comments iniginity scroll
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/components/Ranking/RankingTab.tsx
  src/hooks/useComments.ts
  src/hooks/useInfiniteScroll.ts
  src/styles/theme.ts
Labels: 버그, 개발, 리팩토링

#263 :memo: Fix to prevent multiple events
  src/components/Roulette/RandomRoulette.tsx
Labels: 수정

#264 :recycle: 리팩토링 및 일부 최적화
  src/api/getRankingList.ts
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/components/Ranking/RankingTab.tsx
  src/pages/RankingPage.tsx
Labels: 리팩토링

#265 :recycle: refactoring RandomRoulette
  src/components/Roulette/RandomRoulette.tsx
Labels: 리팩토링

#266 Feature/refactoring #1
  src/components/Common/UI/DimmedLayer.tsx
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#267 :sparkles: attach like action
  src/assets/icons/green-heart-fill.svg
  src/assets/icons/green-heart.svg
  src/components/BestCombinationDetail/Header.tsx
  src/components/Common/Button/Like.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/hooks/useLikedBestCombination.ts
  src/utils/likeCountIntl.ts
Labels: 개발

#268 :recycle: CustomCombinationPage 최적화(임시)
  src/components/CustomCombination/CustomPageModal.tsx
  src/components/CustomCombination/CustomPageWrap.tsx
  src/components/CustomCombination/MyCombinationCard.tsx
  src/components/CustomCombination/MyCombinationStep.tsx
  src/components/CustomCombination/SelectCombination.tsx
  src/services/customCombination/selectIngredients.ts
Labels: 리팩토링

#271 Feature/optimization #2
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/MyPageTab.tsx
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#273 :lipstick: styling like button & comment input wrap
  src/assets/icons/green-heart-fill.svg
  src/assets/icons/green-heart.svg
  src/components/BestCombinationDetail/Header.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Common/Button/Like.tsx
  src/styles/theme.ts
Labels: 개발

#274 :pencil2: 오타수정
  src/components/Comments/CommentInputWrap.tsx
Labels: 핫픽스

#279 :lipstick: 좋아요버튼 추가에 따른 UI 조정
  src/components/Ranking/CombinationRankingCard.tsx
  src/hooks/useLikedBestCombination.ts
Labels: 수정

#280 Feature/optimization #4
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#281 ♻️ Refactoring for PickPage rendering optimization #2
  src/components/BestCombinationPick/AttributePick.tsx
  src/components/BestCombinationPick/DeskTopImage.tsx
  src/pages/BestCombinationPickPage.tsx
Labels: 리팩토링

#283 :recycle: optimize detail page
  src/api/getBestCombination.ts
  src/api/getBestCombinationList.ts
  src/components/BestCombinationDetail/Contents.tsx
  src/components/BestCombinationDetail/Header.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentItem.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#282 Feature/edit modal
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/Roulette/RandomModal.tsx
  src/components/Roulette/RandomRoulette.tsx
Labels: 리팩토링

#285 :sparkles: memoize login status in sessionStorage using recoil-persist
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/layouts/Header.tsx
  src/state/isLoggedIn.ts
Labels: 개발

#286 :recycle: 폰트를 불러오는 link 태그에 preload 를 사용하여 랜더링 차단 시간 단축
  public/index.html
Labels: 리팩토링

#287 :recycle: add debounce at scroll event
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/hooks/useScrollTop.ts
Labels: 리팩토링

#288 Feature/refactoring like
  src/components/MyPage/LikeCard.tsx
  src/components/MyPage/LikeCombinationList.tsx
  src/components/MyPage/MyPageList copy.tsx
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/UserCombinatonList.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Roulette/RandomModalResult.tsx
  src/hooks/useLikedBestCombination.ts
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#289 :sparkles: useCallback 적용
  src/components/Ranking/RankingList.tsx
  src/components/Ranking/RankingTab.tsx
Labels: 개발
