Repository harseille/WhatSsub, pull requests merged in 2022-12, with the labels that each got.

#299 Feature/optimization #5
  public/index.html
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/Common/SandwichInfo.tsx
  src/components/Common/UI/Button.tsx
  src/components/CustomCombination/CombinationRegistration.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/CustomCombination/MyCombinationCard.tsx
  src/components/CustomCombination/NextStepButton.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/pages/MyPagePage.tsx
  src/pages/RandomPickPage.tsx
  src/styles/common.ts
  src/styles/theme.ts
  src/typings/styled.d.ts
Labels: 리팩토링

#312 :bug: solve loader import error
  dist/index.html
  dist/js/836.eff9bf910aca1f2f8506.js
  dist/js/836.f584a45b0994c893a0c4.js
  dist/js/app.50c47b42274094afe0df.js
  dist/js/app.fb8703ddd80a2a492367.js
  dist/js/app.fb8703ddd80a2a492367.js.LICENSE.txt
  src/router.tsx
Labels: 버그

#313 ♻️ modify from lodash to lodash-es for tree_shaking
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/hooks/useScrollTop.ts
Labels: 리팩토링

#314 :recycle: lazily_test
  dist/index.html
  dist/js/app.f296ccef73d24de9c4b7.js
  dist/js/app.f296ccef73d24de9c4b7.js.LICENSE.txt
  dist/js/app.fb8703ddd80a2a492367.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/router.tsx
  webpack/webpack.config.common.js
Labels: 리팩토링

#317 :lipstick: remove highlights from mobile touch
  src/styles/global.ts
Labels: 수정

#318 Feature/page best combination list #5
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Common/LoadingSpinner.tsx
  src/components/Common/SandwichInfo.tsx
  src/components/Ranking/RankingList.tsx
Labels: 리팩토링

#330 :lipstick: add NotFound_Image min-height for layout shift prevention
  src/components/BestCombinationList/NotFoundBestCombinationList.tsx
Labels: 리팩토링

#334 Feature/progressive image
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/assets/images/P_pick_page_desktop_sandwich.png
  src/components/BestCombinationPick/DeskTopImage.tsx
Labels: 리팩토링

#335 :lipstick: modify loading_spinner position
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/Common/LoadingSpinner.tsx
  src/components/Ranking/RankingList.tsx
Labels: 리팩토링

#336 ♻️ add Resize_Image for Progressive Image
  src/assets/images/P_pick_page_desktop_sandwich.png
  src/assets/images/danzzi/danzzi_QM.png
  src/assets/images/danzzi/danzzi_annung.png
  src/assets/images/danzzi/danzzi_crying.png
  src/assets/images/danzzi/danzzi_home.png
  src/assets/images/danzzi/danzzi_home_min.png
  src/assets/images/danzzi/danzzi_question.png
  src/assets/images/danzzi/danzzi_speechless.png
  src/assets/images/danzzi/danzzi_uniform.png
  src/assets/images/pick_page_desktop_sandwich.png
  src/assets/images/pointer.png
  src/assets/images/resize/Resize_danzzi_crying.webp
  src/assets/images/resize/Resize_pick_page_desktop_sandwich.webp
  src/assets/images/resize/Resize_pointer.webp
  src/assets/images/resize/Resize_roulette.webp
  src/assets/images/resize/Resize_startBtn.webp
  src/assets/images/resize/Resize_startBtn1.webp
  src/assets/images/roulette.png
  src/assets/images/startBtn.png
  src/assets/images/startBtn1.png
  src/components/BestCombinationList/NotFoundBestCombinationList.tsx
  src/components/BestCombinationPick/DeskTopImage.tsx
  src/components/Common/SandwichInfo.tsx
  src/components/Roulette/RandomRoulette.tsx
Labels: 리팩토링

#344 Feature/page ranking #5
  src/api/getRankingList.ts
  src/assets/images/rankingBadge/rank_1.png
  src/assets/images/rankingBadge/rank_1.webp
  src/assets/images/rankingBadge/rank_2.png
  src/assets/images/rankingBadge/rank_2.webp
  src/assets/images/rankingBadge/rank_3.png
  src/assets/images/rankingBadge/rank_3.webp
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useInfiniteScroll.ts
  webpack/webpack.config.dev.js
Labels: 개발

#351 :lipstick: modal 취소 버튼 hover 배경색 변경
  src/components/Common/UI/Modal.tsx
Labels: 수정

#356 :recycle: update comment for usability
  .eslintrc.json
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentItem.tsx
  src/pages/BestCombinationDetailPage.tsx
Labels: 리팩토링

#358 :bug: 버튼 오류 수정
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
Labels: 버그

#359 :recycle: refactoring
  .eslintrc.json
  public/index.html
  src/components/BestCombinationAttribute/AttributeBadge.tsx
  src/components/BestCombinationAttribute/AttributeBadgeList.tsx
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/BestCombinationAttribute/AttributeButtonList.tsx
  src/components/BestCombinationAttribute/AttributeListTitle.tsx
  src/components/BestCombinationDetail/Header.tsx
  src/components/BestCombinationPick/AttributeButtonListContainer.tsx
  src/components/BestCombinationPick/AttributePick.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/BestCombinationPick/RefreshButton.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/CustomCombination/CustomPageModal.tsx
  src/components/CustomCombination/CustomPageWrap.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/components/Roulette/RandomModal.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/hooks/useLikedBestCombination.ts
  src/layouts/RootLayout.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/pages/MyPagePage.tsx
  src/pages/NotFound.tsx
  src/pages/RandomPickPage.tsx
Labels: 리팩토링

#360 :recycle: All files refactoring convention
  .eslintrc.json
  src/components/BestCombinationAttribute/AttributeBadge.tsx
  src/components/BestCombinationAttribute/AttributeBadgeList.tsx
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/BestCombinationDetail/Contents.tsx
  src/components/BestCombinationDetail/Header.tsx
  src/components/BestCombinationList/BestCombinationList.tsx
  src/components/BestCombinationPick/NavigateListPageButton.tsx
  src/components/BestCombinationPick/RefreshButton.tsx
  src/components/Comments/CommentInputWrap.tsx
  src/components/Comments/CommentList.tsx
  src/components/Comments/CommentsContainer.tsx
  src/components/Common/Button/Like.tsx
  src/components/Common/Button/LikeRed.tsx
  src/components/Common/Button/Top.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/Common/SandwichInfo.tsx
  src/components/Common/UI/Button.tsx
  src/components/Common/UI/DimmedLayer.tsx
  src/components/Common/UI/Modal.tsx
  src/components/Common/UI/Span.tsx
  src/components/CustomCombination/CombinationRegistration.tsx
  src/components/CustomCombination/CustomPageModal.tsx
  src/components/CustomCombination/CustomPageWrap.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/CustomCombination/MyCombinationCard.tsx
  src/components/CustomCombination/MyCombinationStep.tsx
  src/components/CustomCombination/MyCombinationStepBadge.tsx
  src/components/CustomCombination/NextStepButton.tsx
  src/components/CustomCombination/SelectCombination.tsx
  src/components/CustomCombination/SelectComponent.tsx
  src/components/Ingredient/IngredientCard.tsx
  src/components/Ingredient/IngredientCardList.tsx
  src/components/Ingredient/IngredientInfo.tsx
  src/components/Login/Banner.tsx
  src/components/Login/ButtonList.tsx
  src/components/MyPage/LikeCard.tsx
  src/components/MyPage/LikeCombinationList.tsx
  src/components/MyPage/MyPageList.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/MyPage/UserCombinatonList.tsx
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/components/Ranking/RankingTab.tsx
  src/components/Roulette/RandomModal.tsx
  src/components/Roulette/RandomRoulette.tsx
  src/constants/CustomCombination/constants.ts
  src/layouts/Header.tsx
  src/layouts/HeaderItemsWrap.tsx
  src/pages/HomePage.tsx
  src/pages/RandomPickPage.tsx
  src/services/Random/convertRandomSandwichInfo.ts
  src/styles/theme.ts
  src/typings/ISandwich.ts
  src/typings/styled.d.ts
Labels: 리팩토링

#363 :bug: 랭킹리스트 좋아요수관련 오류 수정
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useLikedBestCombination.ts
  src/hooks/useSetRankingList.ts
  src/state/isPlaying.ts
Labels: 버그

#364 :recycle: myPagePage refactoring
  src/components/MyPage/MyPageContainer.tsx
  src/pages/MyPagePage.tsx
Labels: 리팩토링

#366 :bug: fix back space error on tab buttons
  src/components/MyPage/MyPageContainer.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/Ranking/RankingTab.tsx
Labels: 버그

#368 Feature/page ranking #7
  src/components/Ranking/CombinationRankingCard.tsx
  src/components/Ranking/RankingList.tsx
  src/hooks/useLikedBestCombination.ts
  src/hooks/useSetRankingList.ts
Labels: 수정

#373 :memo: update_README.md
  README.md
  src/api/dbDelete.ts
  src/components/BestCombinationAttribute/AttributeButton.tsx
  src/components/Common/Cards/SandwichInfoCard.tsx
  src/components/CustomCombination/Ingredient.tsx
  src/components/Ingredient/IngredientCard.tsx
  src/components/MyPage/LikeCard.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/MyPage/UserCombinatonList.tsx
  src/components/Ranking/RankingTab.tsx
  src/components/Roulette/RandomModal.tsx
  src/constants/constants.ts
  src/data/PickAttribute.ts
  src/data/ingredients.ts
  src/hooks/useLikedBestCombination.ts
  src/hooks/useSetRankingList.ts
  src/layouts/RootLayout.tsx
  src/pages/BestCombinationDetailPage.tsx
  src/state/IsLoggedIn.ts
  src/utils/convertProgressiveSandwichImage.ts
Labels: 리팩토링
